version: "3.8"

services:
  frontend:
    build: ./Frontend-Proyecto-web-computacion
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - URL_API=http://54.183.120.88:3002
    networks:
      - webnet
    restart: unless-stopped
    command: node ./dist/server/entry.mjs

  backend1:
    build: ./nodejs-mongodb-RestApi_Andoidproyect
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - webnet
    restart: unless-stopped

  backend2:
    build: ./Backend-Proyecto-web-computaci-n
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
    driver: bridge